
INSERT INTO houses (address, id) VALUES 
('Street 1', 1,

26-08-2020 10:00:12 - SQL query throws an exception: - ERROR: syntax error at end of input
  Posição: 58
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.execute(Insert.kt:114)
database.statements.Insert.insertRecursive(Insert.kt:102)
database.statements.Insert.insert(Insert.kt:118)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:49)
exampleModel.MainKt.main(main.kt)

INSERT INTO houses (address, id) VALUES 
('Street 2', 2,

26-08-2020 10:00:12 - SQL query throws an exception: - ERROR: syntax error at end of input
  Posição: 58
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.execute(Insert.kt:114)
database.statements.Insert.insertRecursive(Insert.kt:102)
database.statements.Insert.insert(Insert.kt:118)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:50)
exampleModel.MainKt.main(main.kt)

INSERT INTO author (id, name) VALUES 
(1, 'Halliday',

26-08-2020 10:00:12 - SQL query throws an exception: - ERROR: syntax error at end of input
  Posição: 55
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.execute(Insert.kt:114)
database.statements.Insert.insertRecursive(Insert.kt:102)
database.statements.Insert.insert(Insert.kt:118)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:53)
exampleModel.MainKt.main(main.kt)

INSERT INTO author (author, description, id) VALUES 
(1, 'Halliday',

26-08-2020 10:00:13 - SQL query throws an exception: - ERROR: syntax error at end of input
  Posição: 70
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.execute(Insert.kt:114)
database.statements.Insert.insertRecursive(Insert.kt:102)
database.statements.Insert.insertRecursive(Insert.kt:92)
database.statements.Insert.insert(Insert.kt:118)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:55)
exampleModel.MainKt.main(main.kt)

INSERT INTO author (author, description, id) VALUES 
(1, 'Halliday');'null', 'Fundamentos da Fisica 1', 1,

26-08-2020 10:00:13 - SQL query throws an exception: - ERROR: column "author" of relation "author" does not exist
  Posição: 21
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.execute(Insert.kt:114)
database.statements.Insert.insertRecursive(Insert.kt:102)
database.statements.Insert.insert(Insert.kt:118)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:55)
exampleModel.MainKt.main(main.kt)

INSERT INTO houses (address, id) VALUES 
('Street 1', 1,

26-08-2020 10:01:27 - SQL query throws an exception: - ERROR: syntax error at end of input
  Posição: 58
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.execute(Insert.kt:114)
database.statements.Insert.insertRecursive(Insert.kt:102)
database.statements.Insert.insert(Insert.kt:118)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:49)
exampleModel.MainKt.main(main.kt)

INSERT INTO houses (address, id) VALUES 
('Street 2', 2,

26-08-2020 10:01:27 - SQL query throws an exception: - ERROR: syntax error at end of input
  Posição: 58
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.execute(Insert.kt:114)
database.statements.Insert.insertRecursive(Insert.kt:102)
database.statements.Insert.insert(Insert.kt:118)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:50)
exampleModel.MainKt.main(main.kt)

INSERT INTO author (author, description, id) VALUES 
(1, 'Halliday',

26-08-2020 10:01:27 - SQL query throws an exception: - ERROR: syntax error at end of input
  Posição: 70
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.execute(Insert.kt:114)
database.statements.Insert.insertRecursive(Insert.kt:102)
database.statements.Insert.insertRecursive(Insert.kt:92)
database.statements.Insert.insert(Insert.kt:118)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:55)
exampleModel.MainKt.main(main.kt)

INSERT INTO author (author, description, id) VALUES 
(1, 'Halliday');'null', 'Fundamentos da Fisica 1', 1,

26-08-2020 10:01:27 - SQL query throws an exception: - ERROR: column "author" of relation "author" does not exist
  Posição: 21
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.execute(Insert.kt:114)
database.statements.Insert.insertRecursive(Insert.kt:102)
database.statements.Insert.insert(Insert.kt:118)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:55)
exampleModel.MainKt.main(main.kt)

INSERT INTO houses (address, id) VALUES 
('Street 1', 1);

26-08-2020 10:07:38 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "houses_pkey"
  Detalhe: Key (id)=(1) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:104)
database.statements.Insert.insert(Insert.kt:124)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:49)
exampleModel.MainKt.main(main.kt)

INSERT INTO author (author, description, id) VALUES 
(1, 'Halliday');

26-08-2020 10:07:38 - SQL query throws an exception: - ERROR: column "author" of relation "author" does not exist
  Posição: 21
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:104)
database.statements.Insert.insertRecursive(Insert.kt:93)
database.statements.Insert.insert(Insert.kt:124)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:55)
exampleModel.MainKt.main(main.kt)

INSERT INTO author (author, description, id) VALUES 
(1, 'Halliday');

26-08-2020 10:09:47 - SQL query throws an exception: - ERROR: column "author" of relation "author" does not exist
  Posição: 21
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:104)
database.statements.Insert.insertRecursive(Insert.kt:93)
database.statements.Insert.insert(Insert.kt:124)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:55)
exampleModel.MainKt.main(main.kt)

INSERT INTO books (author, description, id) VALUES 
(1, 'Fundamentos da Fisica 1', 1);

26-08-2020 10:10:05 - SQL query throws an exception: - ERROR: column "author" of relation "books" does not exist
  Posição: 20
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:104)
database.statements.Insert.insert(Insert.kt:124)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:55)
exampleModel.MainKt.main(main.kt)

INSERT INTO author (id, name) VALUES 
(1, 'Halliday');

26-08-2020 10:12:05 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "author_pkey"
  Detalhe: Key (id)=(1) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:106)
database.statements.Insert.insertRecursive(Insert.kt:93)
database.statements.Insert.insert(Insert.kt:126)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:55)
exampleModel.MainKt.main(main.kt)

INSERT INTO houses (address, id) VALUES 
('Street 1', 1);

26-08-2020 10:28:53 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "houses_pkey"
  Detalhe: Key (id)=(1) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:110)
database.statements.Insert.insert(Insert.kt:134)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:49)
exampleModel.MainKt.main(main.kt)

INSERT INTO houses (address, id) VALUES 
('Street 2', 2);

26-08-2020 10:28:53 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "houses_pkey"
  Detalhe: Key (id)=(2) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:110)
database.statements.Insert.insert(Insert.kt:134)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:50)
exampleModel.MainKt.main(main.kt)

INSERT INTO author (id, name) VALUES 
(1, 'Halliday');

26-08-2020 10:30:42 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "author_pkey"
  Detalhe: Key (id)=(1) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:110)
database.statements.Insert.insertRecursive(Insert.kt:97)
database.statements.Insert.insert(Insert.kt:134)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:54)
exampleModel.MainKt.main(main.kt)

INSERT INTO books (author, description, id) VALUES 
('id: 1
name: Halliday', 'Fundamentos da Fisica 1', 1);

26-08-2020 10:32:22 - SQL query throws an exception: - ERROR: column "author" of relation "books" does not exist
  Posição: 20
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:104)
database.statements.Insert.insertRecursive(Insert.kt:91)
database.statements.Insert.insert(Insert.kt:128)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:54)
exampleModel.MainKt.main(main.kt)

INSERT INTO houses (address, id) VALUES 
('Street 1', 1);

26-08-2020 10:34:53 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "houses_pkey"
  Detalhe: Key (id)=(1) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:104)
database.statements.Insert.insert(Insert.kt:128)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:49)
exampleModel.MainKt.main(main.kt)

INSERT INTO houses (address, id) VALUES 
('Street 2', 2);

26-08-2020 10:35:07 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "houses_pkey"
  Detalhe: Key (id)=(2) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:104)
database.statements.Insert.insert(Insert.kt:128)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:50)
exampleModel.MainKt.main(main.kt)

INSERT INTO houses (address, id) VALUES 
('Street 1', 1);

26-08-2020 10:39:41 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "houses_pkey"
  Detalhe: Key (id)=(1) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:104)
database.statements.Insert.insert(Insert.kt:128)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:49)
exampleModel.MainKt.main(main.kt)

INSERT INTO houses (address, id) VALUES 
('Street 2', 2);

26-08-2020 10:39:44 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "houses_pkey"
  Detalhe: Key (id)=(2) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:104)
database.statements.Insert.insert(Insert.kt:128)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:50)
exampleModel.MainKt.main(main.kt)

INSERT INTO houses (address, id) VALUES 
('Street 1', 1);

26-08-2020 10:41:04 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "houses_pkey"
  Detalhe: Key (id)=(1) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:104)
database.statements.Insert.insert(Insert.kt:128)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:49)
exampleModel.MainKt.main(main.kt)

INSERT INTO houses (address, id) VALUES 
('Street 2', 2);

26-08-2020 10:41:21 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "houses_pkey"
  Detalhe: Key (id)=(2) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:104)
database.statements.Insert.insert(Insert.kt:128)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:50)
exampleModel.MainKt.main(main.kt)

INSERT INTO houses (address, id) VALUES 
('Street 1', 1);

26-08-2020 10:43:27 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "houses_pkey"
  Detalhe: Key (id)=(1) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:104)
database.statements.Insert.insert(Insert.kt:128)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:49)
exampleModel.MainKt.main(main.kt)

INSERT INTO houses (address, id) VALUES 
('Street 2', 2);

26-08-2020 10:43:27 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "houses_pkey"
  Detalhe: Key (id)=(2) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:104)
database.statements.Insert.insert(Insert.kt:128)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:50)
exampleModel.MainKt.main(main.kt)

INSERT INTO houses (address, id) VALUES 
('Street 1', 1);

26-08-2020 10:45:33 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "houses_pkey"
  Detalhe: Key (id)=(1) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:104)
database.statements.Insert.insert(Insert.kt:131)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:49)
exampleModel.MainKt.main(main.kt)

INSERT INTO houses (address, id) VALUES 
('Street 2', 2);

26-08-2020 10:45:33 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "houses_pkey"
  Detalhe: Key (id)=(2) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:104)
database.statements.Insert.insert(Insert.kt:131)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:50)
exampleModel.MainKt.main(main.kt)

INSERT INTO author (id, name) VALUES 
(1, 'Halliday');

26-08-2020 10:45:33 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "author_pkey"
  Detalhe: Key (id)=(1) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:104)
database.statements.Insert.insertRecursive(Insert.kt:91)
database.statements.Insert.insertRecursive(Insert.kt:91)
database.statements.Insert.insert(Insert.kt:131)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:54)
exampleModel.MainKt.main(main.kt)

INSERT INTO books (id_author, description, id) VALUES 
(1, 'Fundamentos da Fisica 1', 1);

26-08-2020 10:45:33 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "books_pkey"
  Detalhe: Key (id)=(1) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:104)
database.statements.Insert.insertRecursive(Insert.kt:91)
database.statements.Insert.insert(Insert.kt:131)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:54)
exampleModel.MainKt.main(main.kt)

INSERT INTO users (id_book, id, id_house, name) VALUES 
(1, 1, 1, 'User 1');

26-08-2020 10:45:33 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "users_pkey"
  Detalhe: Key (id)=(1) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:104)
database.statements.Insert.insert(Insert.kt:131)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:54)
exampleModel.MainKt.main(main.kt)

INSERT INTO houses (address, id) VALUES 
('Street 1', 1);

26-08-2020 10:46:17 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "houses_pkey"
  Detalhe: Key (id)=(1) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:104)
database.statements.Insert.insert(Insert.kt:131)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:49)
exampleModel.MainKt.main(main.kt)

INSERT INTO houses (address, id) VALUES 
('Street 2', 2);

26-08-2020 10:46:17 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "houses_pkey"
  Detalhe: Key (id)=(2) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:104)
database.statements.Insert.insert(Insert.kt:131)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:50)
exampleModel.MainKt.main(main.kt)

INSERT INTO author (id, name) VALUES 
(1, 'Halliday');

26-08-2020 10:46:17 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "author_pkey"
  Detalhe: Key (id)=(1) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:104)
database.statements.Insert.insertRecursive(Insert.kt:91)
database.statements.Insert.insertRecursive(Insert.kt:91)
database.statements.Insert.insert(Insert.kt:131)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:54)
exampleModel.MainKt.main(main.kt)

INSERT INTO books (id_author, description, id) VALUES 
(1, 'Fundamentos da Fisica 1', 1);

26-08-2020 10:46:17 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "books_pkey"
  Detalhe: Key (id)=(1) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:104)
database.statements.Insert.insertRecursive(Insert.kt:91)
database.statements.Insert.insert(Insert.kt:131)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:54)
exampleModel.MainKt.main(main.kt)

INSERT INTO users (id_book, id, id_house, name) VALUES 
(1, 1, 1, 'User 1');

26-08-2020 10:46:18 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "users_pkey"
  Detalhe: Key (id)=(1) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:104)
database.statements.Insert.insert(Insert.kt:131)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:54)
exampleModel.MainKt.main(main.kt)

INSERT INTO author (id, name) VALUES 
(1, 'Halliday');

26-08-2020 10:46:18 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "author_pkey"
  Detalhe: Key (id)=(1) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:104)
database.statements.Insert.insertRecursive(Insert.kt:91)
database.statements.Insert.insertRecursive(Insert.kt:91)
database.statements.Insert.insert(Insert.kt:131)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:55)
exampleModel.MainKt.main(main.kt)

INSERT INTO books (id_author, description, id) VALUES 
(1, 'Fundamentos da Fisica 1', 1);

26-08-2020 10:46:18 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "books_pkey"
  Detalhe: Key (id)=(1) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:104)
database.statements.Insert.insertRecursive(Insert.kt:91)
database.statements.Insert.insert(Insert.kt:131)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:55)
exampleModel.MainKt.main(main.kt)

INSERT INTO author (id, name) VALUES 
(1, 'Halliday');

26-08-2020 10:46:43 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "author_pkey"
  Detalhe: Key (id)=(1) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:104)
database.statements.Insert.insertRecursive(Insert.kt:91)
database.statements.Insert.insertRecursive(Insert.kt:91)
database.statements.Insert.insert(Insert.kt:131)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:55)
exampleModel.MainKt.main(main.kt)

INSERT INTO books (id_author, description, id) VALUES 
(1, 'Fundamentos da Fisica 1', 1);

26-08-2020 10:46:43 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "books_pkey"
  Detalhe: Key (id)=(1) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:104)
database.statements.Insert.insertRecursive(Insert.kt:91)
database.statements.Insert.insert(Insert.kt:131)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:55)
exampleModel.MainKt.main(main.kt)

SELECT * FROM users WHERE id = id: 1
description: Fundamentos da Fisica 1
author: id: 1
name: Halliday;

26-08-2020 10:49:33 - SQL query throws an exception: - ERROR: syntax error at or near ":"
  Posição: 34
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:226)
database.DatabaseExecutor.execute(DatabaseExecutor.kt:35)
database.statements.Select.selectAll(Select.kt:94)
database.statements.Select.select(Select.kt:79)
database.statements.Insert.getPrimaryKeysValue(Insert.kt:119)
database.statements.Insert.insertRecursive(Insert.kt:91)
database.statements.Insert.insert(Insert.kt:134)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:54)
exampleModel.MainKt.main(main.kt)

INSERT INTO houses (address, id) VALUES 
('Street 1', 1);

26-08-2020 10:52:32 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "houses_pkey"
  Detalhe: Key (id)=(1) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:110)
database.statements.Insert.insert(Insert.kt:137)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:49)
exampleModel.MainKt.main(main.kt)

INSERT INTO houses (address, id) VALUES 
('Street 2', 2);

26-08-2020 10:52:32 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "houses_pkey"
  Detalhe: Key (id)=(2) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:110)
database.statements.Insert.insert(Insert.kt:137)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:50)
exampleModel.MainKt.main(main.kt)

INSERT INTO houses (address, id) VALUES 
('Street 1', 1);

26-08-2020 11:00:46 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "houses_pkey"
  Detalhe: Key (id)=(1) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:126)
database.statements.Insert.insert(Insert.kt:153)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:49)
exampleModel.MainKt.main(main.kt)

INSERT INTO houses (address, id) VALUES 
('Street 2', 2);

26-08-2020 11:00:46 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "houses_pkey"
  Detalhe: Key (id)=(2) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:126)
database.statements.Insert.insert(Insert.kt:153)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:50)
exampleModel.MainKt.main(main.kt)

INSERT INTO houses (address, id) VALUES 
('Street 1', 1);

26-08-2020 11:03:07 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "houses_pkey"
  Detalhe: Key (id)=(1) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:126)
database.statements.Insert.insert(Insert.kt:155)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:49)
exampleModel.MainKt.main(main.kt)

INSERT INTO houses (address, id) VALUES 
('Street 2', 2);

26-08-2020 11:03:07 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "houses_pkey"
  Detalhe: Key (id)=(2) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:126)
database.statements.Insert.insert(Insert.kt:155)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:50)
exampleModel.MainKt.main(main.kt)

CREATE TABLE IF NOT EXISTS users (
id int primary key not null,
id_house int not null,
name varchar(255) not null);
CREATE SEQUENCE IF NOT EXISTS users_seq INCREMENT 1 MINVALUE 1 START 1;
ALTER TABLE users ALTER COLUMN id SET DEFAULT nextval('users_seq');


ALTER TABLE users ADD COLUMN id_book INT;

ALTER TABLE users ADD CONSTRAINT fk_user_book
FOREIGN KEY (id_book)
REFERENCES books(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE users ADD CONSTRAINT fk_user_house
FOREIGN KEY (id_house)
REFERENCES houses(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tasks ADD CONSTRAINT fk_user_task
FOREIGN KEY (id_user)
REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE;

26-08-2020 11:41:56 - SQL query throws an exception: - ERROR: column "id_user" referenced in foreign key constraint does not exist
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.executeUpdate(PgStatement.java:247)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:65)
database.DatabaseExecutor.executeOperation$default(DatabaseExecutor.kt:53)
database.statements.Create.execute(Create.kt:201)
database.facades.ModelQueryFacade.<init>(ModelQueryFacade.kt:22)
exampleModel.MainKt.main(main.kt:26)
exampleModel.MainKt.main(main.kt)

INSERT INTO users (id_book, id, id_house, name) VALUES 
(1, 1, 1, 'User 1');

26-08-2020 11:41:57 - SQL query throws an exception: - ERROR: relation "users" does not exist
  Posição: 13
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:126)
database.statements.Insert.insert(Insert.kt:185)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:47)
exampleModel.MainKt.main(main.kt)

SELECT * FROM users WHERE id = 1;

26-08-2020 11:41:57 - SQL query throws an exception: - ERROR: relation "users" does not exist
  Posição: 15
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:226)
database.DatabaseExecutor.execute(DatabaseExecutor.kt:35)
database.statements.Select.selectAll(Select.kt:94)
database.statements.Select.select(Select.kt:79)
database.statements.Insert.getPrimaryKeysValue(Insert.kt:168)
database.statements.Insert.insertRecursive(Insert.kt:129)
database.statements.Insert.insert(Insert.kt:185)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:47)
exampleModel.MainKt.main(main.kt)

CREATE TABLE IF NOT EXISTS users (
id int primary key not null,
id_house int not null,
name varchar(255) not null);
CREATE SEQUENCE IF NOT EXISTS users_seq INCREMENT 1 MINVALUE 1 START 1;
ALTER TABLE users ALTER COLUMN id SET DEFAULT nextval('users_seq');


ALTER TABLE users ADD COLUMN id_book INT;

ALTER TABLE users ADD CONSTRAINT fk_user_book
FOREIGN KEY (id_book)
REFERENCES books(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE users ADD CONSTRAINT fk_user_house
FOREIGN KEY (id_house)
REFERENCES houses(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tasks ADD CONSTRAINT fk_user_task
FOREIGN KEY (id_user)
REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE;

26-08-2020 11:42:45 - SQL query throws an exception: - ERROR: column "id_user" referenced in foreign key constraint does not exist
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.executeUpdate(PgStatement.java:247)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:65)
database.DatabaseExecutor.executeOperation$default(DatabaseExecutor.kt:53)
database.statements.Create.execute(Create.kt:201)
database.facades.ModelQueryFacade.<init>(ModelQueryFacade.kt:22)
exampleModel.MainKt.main(main.kt:26)
exampleModel.MainKt.main(main.kt)

INSERT INTO houses (address, id) VALUES 
('Street 1', 1);

26-08-2020 11:42:45 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "houses_pkey"
  Detalhe: Key (id)=(1) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:126)
database.statements.Insert.insert(Insert.kt:185)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:42)
exampleModel.MainKt.main(main.kt)

INSERT INTO houses (address, id) VALUES 
('Street 2', 2);

26-08-2020 11:42:45 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "houses_pkey"
  Detalhe: Key (id)=(2) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:126)
database.statements.Insert.insert(Insert.kt:185)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:43)
exampleModel.MainKt.main(main.kt)

INSERT INTO books (id_author, description, id) VALUES 
(1, 'Fundamentos da Fisica 1', 1);

26-08-2020 11:42:45 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "books_pkey"
  Detalhe: Key (id)=(1) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:126)
database.statements.Insert.insert(Insert.kt:185)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:45)
exampleModel.MainKt.main(main.kt)

INSERT INTO users (id_book, id, id_house, name) VALUES 
(1, 1, 1, 'User 1');

26-08-2020 11:42:45 - SQL query throws an exception: - ERROR: relation "users" does not exist
  Posição: 13
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:126)
database.statements.Insert.insert(Insert.kt:185)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:47)
exampleModel.MainKt.main(main.kt)

SELECT * FROM users WHERE id = 1;

26-08-2020 11:42:45 - SQL query throws an exception: - ERROR: relation "users" does not exist
  Posição: 15
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:226)
database.DatabaseExecutor.execute(DatabaseExecutor.kt:35)
database.statements.Select.selectAll(Select.kt:94)
database.statements.Select.select(Select.kt:79)
database.statements.Insert.getPrimaryKeysValue(Insert.kt:168)
database.statements.Insert.insertRecursive(Insert.kt:129)
database.statements.Insert.insert(Insert.kt:185)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:47)
exampleModel.MainKt.main(main.kt)

CREATE TABLE IF NOT EXISTS users (
id int primary key not null,
id_house int not null,
name varchar(255) not null);
CREATE SEQUENCE IF NOT EXISTS users_seq INCREMENT 1 MINVALUE 1 START 1;
ALTER TABLE users ALTER COLUMN id SET DEFAULT nextval('users_seq');


ALTER TABLE users ADD COLUMN id_book INT;

ALTER TABLE users ADD CONSTRAINT fk_user_book
FOREIGN KEY (id_book)
REFERENCES books(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE users ADD CONSTRAINT fk_user_house
FOREIGN KEY (id_house)
REFERENCES houses(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tasks ADD CONSTRAINT fk_user_task
FOREIGN KEY (id_user)
REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE;

26-08-2020 11:42:58 - SQL query throws an exception: - ERROR: column "id_user" referenced in foreign key constraint does not exist
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.executeUpdate(PgStatement.java:247)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:65)
database.DatabaseExecutor.executeOperation$default(DatabaseExecutor.kt:53)
database.statements.Create.execute(Create.kt:201)
database.facades.ModelQueryFacade.<init>(ModelQueryFacade.kt:22)
exampleModel.MainKt.main(main.kt:26)
exampleModel.MainKt.main(main.kt)

INSERT INTO houses (address, id) VALUES 
('Street 1', 1);

26-08-2020 11:42:58 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "houses_pkey"
  Detalhe: Key (id)=(1) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:126)
database.statements.Insert.insert(Insert.kt:185)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:42)
exampleModel.MainKt.main(main.kt)

INSERT INTO houses (address, id) VALUES 
('Street 2', 2);

26-08-2020 11:42:58 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "houses_pkey"
  Detalhe: Key (id)=(2) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:126)
database.statements.Insert.insert(Insert.kt:185)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:43)
exampleModel.MainKt.main(main.kt)

INSERT INTO books (id_author, description, id) VALUES 
(1, 'Fundamentos da Fisica 1', 1);

26-08-2020 11:42:58 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "books_pkey"
  Detalhe: Key (id)=(1) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:126)
database.statements.Insert.insert(Insert.kt:185)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:45)
exampleModel.MainKt.main(main.kt)

INSERT INTO users (id_book, id, id_house, name) VALUES 
(1, 1, 1, 'User 1');

26-08-2020 11:42:59 - SQL query throws an exception: - ERROR: relation "users" does not exist
  Posição: 13
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:126)
database.statements.Insert.insert(Insert.kt:185)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:47)
exampleModel.MainKt.main(main.kt)

SELECT * FROM users WHERE id = 1;

26-08-2020 11:42:59 - SQL query throws an exception: - ERROR: relation "users" does not exist
  Posição: 15
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:226)
database.DatabaseExecutor.execute(DatabaseExecutor.kt:35)
database.statements.Select.selectAll(Select.kt:94)
database.statements.Select.select(Select.kt:79)
database.statements.Insert.getPrimaryKeysValue(Insert.kt:168)
database.statements.Insert.insertRecursive(Insert.kt:129)
database.statements.Insert.insert(Insert.kt:185)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:47)
exampleModel.MainKt.main(main.kt)

CREATE TABLE IF NOT EXISTS users (
id int primary key not null,
id_house int not null,
name varchar(255) not null);
CREATE SEQUENCE IF NOT EXISTS users_seq INCREMENT 1 MINVALUE 1 START 1;
ALTER TABLE users ALTER COLUMN id SET DEFAULT nextval('users_seq');


ALTER TABLE users ADD COLUMN id_book INT;

ALTER TABLE users ADD CONSTRAINT fk_user_book
FOREIGN KEY (id_book)
REFERENCES books(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE users ADD CONSTRAINT fk_user_house
FOREIGN KEY (id_house)
REFERENCES houses(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tasks ADD CONSTRAINT fk_user_task
FOREIGN KEY (id_user)
REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE;

26-08-2020 11:43:13 - SQL query throws an exception: - ERROR: column "id_user" referenced in foreign key constraint does not exist
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.executeUpdate(PgStatement.java:247)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:65)
database.DatabaseExecutor.executeOperation$default(DatabaseExecutor.kt:53)
database.statements.Create.execute(Create.kt:201)
database.facades.ModelQueryFacade.<init>(ModelQueryFacade.kt:22)
exampleModel.MainKt.main(main.kt:26)
exampleModel.MainKt.main(main.kt)

INSERT INTO houses (address, id) VALUES 
('Street 1', 1);

26-08-2020 11:43:13 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "houses_pkey"
  Detalhe: Key (id)=(1) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:126)
database.statements.Insert.insert(Insert.kt:185)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:42)
exampleModel.MainKt.main(main.kt)

INSERT INTO houses (address, id) VALUES 
('Street 2', 2);

26-08-2020 11:43:13 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "houses_pkey"
  Detalhe: Key (id)=(2) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:126)
database.statements.Insert.insert(Insert.kt:185)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:43)
exampleModel.MainKt.main(main.kt)

INSERT INTO books (id_author, description, id) VALUES 
(1, 'Fundamentos da Fisica 1', 1);

26-08-2020 11:43:13 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "books_pkey"
  Detalhe: Key (id)=(1) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:126)
database.statements.Insert.insert(Insert.kt:185)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:45)
exampleModel.MainKt.main(main.kt)

INSERT INTO users (id_book, id, id_house, name) VALUES 
(1, 1, 1, 'User 1');

26-08-2020 11:43:13 - SQL query throws an exception: - ERROR: relation "users" does not exist
  Posição: 13
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:126)
database.statements.Insert.insert(Insert.kt:185)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:47)
exampleModel.MainKt.main(main.kt)

SELECT * FROM users WHERE id = 1;

26-08-2020 11:43:13 - SQL query throws an exception: - ERROR: relation "users" does not exist
  Posição: 15
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:226)
database.DatabaseExecutor.execute(DatabaseExecutor.kt:35)
database.statements.Select.selectAll(Select.kt:94)
database.statements.Select.select(Select.kt:79)
database.statements.Insert.getPrimaryKeysValue(Insert.kt:168)
database.statements.Insert.insertRecursive(Insert.kt:129)
database.statements.Insert.insert(Insert.kt:185)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:47)
exampleModel.MainKt.main(main.kt)

CREATE TABLE IF NOT EXISTS users (
id int primary key not null,
id_house int not null,
name varchar(255) not null);
CREATE SEQUENCE IF NOT EXISTS users_seq INCREMENT 1 MINVALUE 1 START 1;
ALTER TABLE users ALTER COLUMN id SET DEFAULT nextval('users_seq');


ALTER TABLE users ADD COLUMN id_book INT;

ALTER TABLE users ADD CONSTRAINT fk_user_book
FOREIGN KEY (id_book)
REFERENCES books(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE users ADD CONSTRAINT fk_user_house
FOREIGN KEY (id_house)
REFERENCES houses(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE tasks ADD CONSTRAINT fk_user_task
FOREIGN KEY (id_user)
REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE;

26-08-2020 11:43:58 - SQL query throws an exception: - ERROR: column "id_user" referenced in foreign key constraint does not exist
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.executeUpdate(PgStatement.java:247)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:65)
database.DatabaseExecutor.executeOperation$default(DatabaseExecutor.kt:53)
database.statements.Create.execute(Create.kt:201)
database.facades.ModelQueryFacade.<init>(ModelQueryFacade.kt:22)
exampleModel.MainKt.main(main.kt:26)
exampleModel.MainKt.main(main.kt)

INSERT INTO houses (address, id) VALUES 
('Street 1', 1);

26-08-2020 11:43:59 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "houses_pkey"
  Detalhe: Key (id)=(1) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:126)
database.statements.Insert.insert(Insert.kt:185)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:42)
exampleModel.MainKt.main(main.kt)

INSERT INTO houses (address, id) VALUES 
('Street 2', 2);

26-08-2020 11:43:59 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "houses_pkey"
  Detalhe: Key (id)=(2) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:126)
database.statements.Insert.insert(Insert.kt:185)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:43)
exampleModel.MainKt.main(main.kt)

INSERT INTO books (id_author, description, id) VALUES 
(1, 'Fundamentos da Fisica 1', 1);

26-08-2020 11:43:59 - SQL query throws an exception: - ERROR: duplicate key value violates unique constraint "books_pkey"
  Detalhe: Key (id)=(1) already exists.
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:126)
database.statements.Insert.insert(Insert.kt:185)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:45)
exampleModel.MainKt.main(main.kt)

INSERT INTO users (id_book, id, id_house, name) VALUES 
(1, 1, 1, 'User 1');

26-08-2020 11:43:59 - SQL query throws an exception: - ERROR: relation "users" does not exist
  Posição: 13
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
database.DatabaseExecutor.executeOperation(DatabaseExecutor.kt:63)
database.statements.Insert.insertRecursive(Insert.kt:126)
database.statements.Insert.insert(Insert.kt:185)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:47)
exampleModel.MainKt.main(main.kt)

SELECT * FROM users WHERE id = 1;

26-08-2020 11:43:59 - SQL query throws an exception: - ERROR: relation "users" does not exist
  Posição: 15
org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:226)
database.DatabaseExecutor.execute(DatabaseExecutor.kt:35)
database.statements.Select.selectAll(Select.kt:94)
database.statements.Select.select(Select.kt:79)
database.statements.Insert.getPrimaryKeysValue(Insert.kt:168)
database.statements.Insert.insertRecursive(Insert.kt:129)
database.statements.Insert.insert(Insert.kt:185)
database.facades.ModelQueryFacade.insert(ModelQueryFacade.kt:72)
exampleModel.MainKt.main(main.kt:47)
exampleModel.MainKt.main(main.kt)
